# Generated by Django 6.1 on 2026-08-08 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('brand_snapshot', models.CharField(max_length=100)),
                ('vehicle_name_snapshot', models.CharField(max_length=150)),
                ('ex_showroom_price_at_query', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('on_road_price_calculated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('source_page', models.CharField(default='calculator', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_exported', models.BooleanField(default=False)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='calculator.state')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='portfolio.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
