# Generated by Django 6.1 on 2026-10-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='articles/', verbose_name='Featured Image'),
        ),
    ]
