# Generated by Django 6.1 on 2026-08-08 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='Image URL or Cloudinary URL', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('body_type', models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('mpv', 'MPV'), ('luxury', 'Luxury'), ('ev', 'Electric Vehicle')], default='suv', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('ex_showroom_price', models.DecimalField(decimal_places=2, help_text='Base ex-showroom price in INR', max_digits=12)),
                ('key_specs', models.JSONField(blank=True, default=dict, help_text="e.g. {'engine': '1.5L Turbo', 'mileage': '18.2 kmpl', 'power': '115 bhp', 'seating': 5}")),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='portfolio.brand')),
            ],
            options={
                'ordering': ['-is_featured', 'brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.vehicle')),
            ],
            options={
                'ordering': ['-is_primary', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
                ('ex_showroom_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('transmission', models.CharField(default='Manual', help_text='Manual, Automatic, AMT, DCT', max_length=50)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='portfolio.vehicle')),
            ],
            options={
                'ordering': ['ex_showroom_price'],
            },
        ),
    ]
