# Generated by Django 6.1 on 2026-08-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='data_source',
            field=models.CharField(default='master_db_import', help_text='master_db_import | manual', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ev_hybrid_cng_flag',
            field=models.CharField(default='No', help_text='No, EV, Hybrid, CNG, Hybrid/CNG, Hybrid/Petrol', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='True for TBA prices or corrupt seat values'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(blank=True, help_text='Seating capacity', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting ex-showroom price in INR', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='top_variant_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Top variant ex-showroom price in INR', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, default='Manual/Automatic', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(default='SUV', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ex_showroom_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ex-showroom price (alias/starting price)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='key_specs',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'engine': '1.5L Turbo', 'mileage': '18.2 kmpl'}"),
        ),
        migrations.AlterField(
            model_name='vehiclevariant',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclevariant',
            name='transmission',
            field=models.CharField(default='Manual', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('brand', 'name')},
        ),
    ]
