# Generated by Django 6.1 on 2026-08-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_vehicle_data_source_vehicle_ev_hybrid_cng_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_tba',
            field=models.BooleanField(default=False, help_text='True if car prices are to be announced'),
        ),
    ]
