# Generated by Django 6.1 on 2026-08-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_vehicle_is_tba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
    ]
