# Generated by Django 6.1 on 2026-08-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_vehicleimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed vehicle overview and description'),
        ),
    ]
