# Generated by Django 6.1 on 2026-09-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_vehicle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image_url',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='vehicle_images/'),
        ),
    ]
