# Generated by Django 6.1 on 2026-08-08 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dealer Handling & Logistics', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('is_default_included', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g. DL, MH, KA, GJ, CH', max_length=10, unique=True)),
                ('price_basis', models.CharField(choices=[('ex_showroom', 'Ex-Showroom Price'), ('pre_gst', 'Pre-GST Price (Gujarat, Chandigarh, Jharkhand basis)')], default='ex_showroom', max_length=20)),
                ('pre_gst_factor', models.DecimalField(decimal_places=4, default=0.72, help_text='Pre-GST price factor if applicable (e.g. 0.72 = 72% of ex-showroom)', max_digits=5)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=600.0, max_digits=10)),
                ('smart_card_fee', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('hsrp_fee', models.DecimalField(decimal_places=2, default=400.0, max_digits=10)),
                ('hypothecation_fee', models.DecimalField(decimal_places=2, default=1500.0, help_text='Charged if vehicle is financed', max_digits=10)),
                ('fastag_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoadTaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('all', 'All Fuel Types'), ('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric / EV'), ('hybrid', 'Hybrid')], default='all', max_length=20)),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for no upper bound', max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Rate as decimal e.g. 0.13 = 13%, 0.00 = 0% EV rate', max_digits=5)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_slabs', to='calculator.state')),
            ],
            options={
                'ordering': ['state', 'min_price'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_percent', models.DecimalField(decimal_places=2, default=3.5, help_text='Percentage of ex-showroom price (e.g. 3.50 = 3.5%)', max_digits=5)),
                ('state', models.ForeignKey(blank=True, help_text='Leave blank for national fallback default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_estimates', to='calculator.state')),
            ],
        ),
    ]
