# Generated by Django 6.1 on 2026-08-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
        ('portfolio', '0002_vehicle_data_source_vehicle_ev_hybrid_cng_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='data_source_note',
            field=models.TextField(blank=True, default='Estimated 2026 road-tax basis; see PDF methodology.', help_text='Surface in UI calculator disclaimer'),
        ),
        migrations.AddField(
            model_name='state',
            name='misc_fee',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Fixed misc charges baked into spreadsheet OTR', max_digits=10),
        ),
        migrations.CreateModel(
            name='VehicleStateEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_otr', models.DecimalField(decimal_places=2, help_text='Precomputed starting variant OTR price', max_digits=12)),
                ('top_otr', models.DecimalField(decimal_places=2, help_text='Precomputed top variant OTR price', max_digits=12)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_estimates', to='calculator.state')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_estimates', to='portfolio.vehicle')),
            ],
            options={
                'ordering': ['vehicle', 'state'],
                'unique_together': {('vehicle', 'state')},
            },
        ),
    ]
