# Generated by Django 6.1 on 2026-08-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_state_data_source_note_state_misc_fee_and_more'),
        ('portfolio', '0003_vehicle_is_tba'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateOnRoadPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ex_showroom', models.BigIntegerField(blank=True, null=True)),
                ('top_ex_showroom', models.BigIntegerField(blank=True, null=True)),
                ('start_on_road', models.BigIntegerField(blank=True, null=True)),
                ('top_on_road', models.BigIntegerField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_prices', to='portfolio.vehicle')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_prices', to='calculator.state')),
            ],
            options={
                'unique_together': {('car', 'state')},
            },
        ),
    ]
