# Generated by Django 6.1 on 2026-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_stateonroadprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadtaxslab',
            name='cess_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Additional road safety/green cess rate as decimal e.g. 0.01 = 1% on tax or ex-showroom', max_digits=5),
        ),
        migrations.AddField(
            model_name='roadtaxslab',
            name='flat_cess',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Flat cess amount in INR e.g. 500.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='roadtaxslab',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Slab-specific RTO notification notes'),
        ),
    ]
