# Generated by Django 6.1 on 2026-08-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_roadtaxslab_cess_rate_roadtaxslab_flat_cess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadtaxslab',
            name='company_surcharge_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Additional tax rate for company registration e.g. 0.04 = +4%', max_digits=5),
        ),
        migrations.AddField(
            model_name='roadtaxslab',
            name='effective_from',
            field=models.DateField(default='2026-01-01', help_text='Rule effective start date'),
        ),
        migrations.AddField(
            model_name='roadtaxslab',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Rule effective expiry date', null=True),
        ),
        migrations.AddField(
            model_name='roadtaxslab',
            name='green_tax_flat',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Green tax / environmental levy in INR', max_digits=10),
        ),
        migrations.AddField(
            model_name='roadtaxslab',
            name='last_verified',
            field=models.DateField(default='2026-08-01', help_text='Last verification date against RTO gazette'),
        ),
        migrations.AddField(
            model_name='roadtaxslab',
            name='municipal_cess_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='City municipal / infrastructure cess rate', max_digits=5),
        ),
        migrations.AddField(
            model_name='roadtaxslab',
            name='notification_number',
            field=models.CharField(default='GSR-2026/RTO-STD', help_text='Official RTO gazette notification ID', max_length=150),
        ),
        migrations.AddField(
            model_name='roadtaxslab',
            name='ownership_type',
            field=models.CharField(choices=[('all', 'All Ownership Types'), ('individual', 'Individual Ownership'), ('company', 'Company / Corporate Ownership')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='roadtaxslab',
            name='source_url',
            field=models.URLField(default='https://morth.nic.in', help_text='Official RTO notification portal URL', max_length=500),
        ),
        migrations.AddField(
            model_name='roadtaxslab',
            name='temp_registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Temporary inter-state RTO registration fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='roadtaxslab',
            name='cess_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Additional road safety/transport cess rate as decimal e.g. 0.01 = 1%', max_digits=5),
        ),
    ]
